### PR TITLE
DROOLS-1096 Kie Camel not working on Fuse 6.3 EAP.

### PR DESCRIPTION
**Pull request by dvirgiln**
https://issues.jboss.org/browse/DROOLS-1096

### CODE REVIEW

**Comment by psiroky** [comment]
Thanks for the fix @dvirgiln. I think I do not understand why need the changes in org-kie and org-jbpm modules. I've tried to build the bpms-distro-zip with and without those (and keeping the slot change in aether) and the end result in exactly the same. It seems we only need that slot change in the aether. Or am I overlooking something?

**Comment by dvirgiln** [comment]
take a look.

**Comment by psiroky** [comment]
@dvirgiln yes, I am looking. I don't see any difference in the end distributions (kie-eap-distribution  and kie-eap-distributions-bpms-layer).

**Comment by dvirgiln** [comment]
yes one file changed. that would be enough. we need the aether module to go on another slot

**Comment by psiroky** [comment]
@dvirgiln ok, good. I will merge this then.

**Comment by psiroky** [comment]
Merged into 6.4.x (https://github.com/jboss-integration/kie-eap-modules/commit/015371a0156537a647db04c14dec90ae37dfbd2c) and cherry-picked to master.

**Pull request closed without merging**
