### PR TITLE
[JBPM-4900] add missing dashbulider deps in jbpm module

### PR DESCRIPTION
**Pull request by psiroky**
@romartin could you please review?

### CODE REVIEW

**Comment by mswiderski** [comment]
thanks @psiroky 

once merged can we cherry pick this to 6.4.x too?

**Comment by psiroky** [comment]
@maciejs yes, we definitely should

**Comment by mswiderski** [comment]
+1

**Comment by romartin** [comment]
@mswiderski @psiroky thx for looking into that , i was far from my desktop...

**Pull request merged**
