### PR TITLE
Replace modules plugin with static resources + assembly plugin

### PR DESCRIPTION
**Pull request by psiroky**
@romartin could you please quickly check this? The diff is huge because of the deletes / moves, but would be great if you could just skim over it to see there aren't any obvious errors.

Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/201

### CODE REVIEW

**Comment by romartin** [comment]
@psiroky Hello, verified locally, sounds good. Do you want me to merge this one? I would say that better letting the fuse guys know about this, so they can give it a try. We don't have right now other way to try this on runtime....

**Comment by psiroky** [comment]
I am planning to create some tests directly in this repo. We can leave the PR open, but it may take me a while until the tests are ready.

**Comment by romartin** [comment]
@psiroky oh should be nice! as the errors often to appear only at runtime.. so better if we can do some checks before :) thx

**Comment by psiroky** [comment]
@romartin I created a very basic (smoke) test and fixed few additional issues discovered by that test. Test infrastructure is in place as well (Arquillian-based as we want to be abe to run in-container tests), so adding new tests should be quite easy.

**Comment by romartin** [comment]
+1

**Pull request merged**
