### PR TITLE
ENTESB-4090 - kie-remote modules fix

### PR DESCRIPTION
**Pull request by mrietveld**
Please also cherry-pick to master. 

This relates to 
- https://issues.jboss.org/browse/ENTESB-4090
- https://bugzilla.redhat.com/show_bug.cgi?id=1267906 (blocker 6.3.x)

### CODE REVIEW

**Comment by mrietveld** [comment]
@dvirgiln This is the pull request we talked about.

**Comment by mrietveld** [comment]
Please wait to merge.

**Comment by mrietveld** [comment]
@psiroky Please merge, thanks!

**Comment by dvirgiln** [comment]
yes @mrietveld . I think then with this fix, the kie-eap-distributions-bpms-layer will include these dependencies. Once this is merged and the nightly build is done, i can check the jbpm remote scenario is working. 

Many thanks Marco

**Comment by mrietveld** [comment]
We might also need to cherry-pick this to 6.2.x, confirming this now.

**Comment by psiroky** [comment]
It seems additional changes are needed. See the Jenkins build console:

```
16:03:27 [INFO] ********************* Missing dependencies ******************************
16:03:27 [INFO] Module/s [org.kie.remote:main ] require [org.kie.remote:kie-remote-common:jar:6.3.1-SNAPSHOT] and this depedency is not present in any module. This artifact should be added or excluded
16:03:27 [INFO] Module/s [org.kie.remote:main ] require [org.kie.remote.ws:kie-remote-ws-common:jar:6.3.1-SNAPSHOT] and this depedency is not present in any module. This artifact should be added or excluded
```

Just out of curiosity, why were these dependencies excluded in the first place? @romartin do you know by any chance?

**Comment by mrietveld** [comment]
@psiroky, see https://github.com/jboss-integration/kie-eap-modules/pull/2 :)

**Comment by psiroky** [comment]
I am looking at  #2 (this PR), but I am not sure what should I see :)

**Comment by mrietveld** [comment]
Ehmm.. 

https://github.com/jboss-integration/kie-eap-modules/pull/2/files#diff-9ba3c281177185ba16803b4783a6f8aaL30

?

**Comment by mrietveld** [comment]
Oh, @psiroky, sorry, I though we were on the other PR. 

Ooops!

**Comment by mrietveld** [comment]
@psiroky Uhm, the kie-remote-\* infrastructure has changed a bit since 6.0.x, those jars were probably not needed then, but are needed now.

**Comment by romartin** [comment]
Petr I don't understand at all your comment... Anyway, what the plugin say it's just that there exist a dependency, you can exclude it (using mvn dependency exclusion in the plugin configuration) I you know it's an optional or runtime dependency that is no longer needed for the module scope, or add the dependency if it's really required

**Comment by psiroky** [comment]
Thanks for the info @mrietveld.

The build is still failing though, would you be able to look at that?

**Comment by mrietveld** [comment]
@psiroky Updated and fixed.

**Comment by psiroky** [comment]
Thanks @mrietveld

+1, I will merge this asap.

**Comment by psiroky** [comment]
Merged into 6.3.x and master.

Please let me know/submit new PR if it needs to go into 6.2.x as well.

**Comment by mrietveld** [comment]
@psiroky Yes, please cherry-pick to 6.2.x. 

@dvirgiln ^^ module fix.

**Pull request closed without merging**
