### PR TITLE
Upgrade and fix kie-fuse-config-editor

### PR DESCRIPTION
**Pull request by psiroky**
@dvirgiln would you mind looking at this? I am not 100% sure about the changes. Also is there some easy way to test this?

### CODE REVIEW

**Comment by psiroky** [comment]
@romartin if you would find some time to look at this as well, that would be great.

**Comment by romartin** [comment]
Hi @psiroky ,

Thanks for looking into it! Well i have build it locally fine, but looking at the code and the generated jar no sure if we are missing something here... My local changes were same as your commit, so moving to the use of the wildfly config editor artifact, but not sure if only specifying the layer name in https://github.com/psiroky/kie-eap-modules/blob/upgrade-fuse-config-editor/kie-fuse-config-editor/src/main/java/org/jboss/integration/fuse/bxms/config/BxMSIntegrationConfigEditor.java#L37 is enought. So we are providing the name for our custom module layer, but how is it "copied" into the wildfly installation? Are we missing something here? https://github.com/psiroky/kie-eap-modules/blob/upgrade-fuse-config-editor/kie-fuse-config-editor/src/main/java/org/jboss/integration/fuse/bxms/config/BxMSIntegrationConfigEditor.java#L49 Not sure..

**Comment by psiroky** [comment]
I've basically taken what we already have (https://github.com/jboss-integration/kie-eap-modules/blob/master/kie-fuse-config-editor/src/main/java/org/jboss/integration/fuse/bxms/Config/BxMSIntegrationConfigEditor.java) and tried to make it work with the new API. I am by far not sure this is correct. We really need some tests here. Will take a look at that.

**Comment by romartin** [comment]
Yes agreed. Ok Petr let me know how this moves forward... thx

**Comment by mbiarnes** [comment]
@psiroky : this PR also has to be backported to 6.4.x branch. When building kie-eap-modules from scratch locally having removed before some .m2/repository/org/... we have the same problem.

**Comment by dvirgiln** [comment]
Hi @psiroky ,

I think is missing a services file as we have on fuse-integration package:

https://github.com/jboss-integration/fuse-bxms-integ/tree/master/release/eap/config/src/main/resources/META-INF/services

As you see on the fuse-integration config, we are installing the bpms layer, 

https://github.com/jboss-integration/fuse-bxms-integ/blob/master/release/eap/config/src/main/java/org/jboss/integration/fuse/config/FuseIntegrationConfigPlugin.java

So after this bpms config is done on KIE side, then  a PR on fuse-bxms-integration is required for not installing the bpms layer.

Then it is required to include on your eap distro the config jar

https://github.com/jboss-integration/fuse-bxms-integ/blob/master/release/eap/distro/assembly.xml#L81-L86

**Comment by dvirgiln** [comment]
If evertything is ok, then to test this would be enough installing the fuse-bxms-integ unsin the fuse-bxms-integ eap installer:

https://github.com/jboss-integration/fuse-bxms-integ/tree/master/release/eap/installer

**Comment by psiroky** [comment]
As discussed with @dvirgiln, we currently don't even need this config module. Fuse integration installer is simply taking the kie-eap-modules-distribution zip and unzips that over EAP. We may reconsider adding a specific installer in this repo, but until then we will just remove it , see #12 (master) and #11 (6.4.x).

**Pull request closed without merging**
